use std::collections::HashMap;
use glam::Vec4;
use rayon::iter::{IntoParallelIterator, ParallelIterator};

use crate::utils::CharacterGlyph;

///
#[derive(Clone, Copy, Debug)]
struct Point {
    x: f32,
    y: f32,
}

impl Point {
    // An infinite/maximum distance marker for initialization
    fn infinity() -> Self {
        Self { x: 9999.0, y: 9999.0 }
    }

    fn length_sq(&self) -> f32 {
        self.x * self.x + self.y * self.y
    }
}

/// Contains the raw bitmap information about a specific glyph
/// 
/// This is a temporary struct generated by rayon threads.
struct SdfGlyph {
    ch: char,
    metrics: fontdue::Metrics,
    bitmap: Vec<u8>,
    width: u32,
    height: u32,
}

/// Generate an signed distance field (sdf) font atlas by rasterizing a ttf font
/// 
/// * 'font' - the font containing the glyph metrics
/// * 'size' - the size of the bitmap atlas in pixels
/// * 'scale' - the size to rasterize the characters with, in pixels per em unit
/// * 'radius' - spacing between bitmap characters
pub fn gen_font_atlas(font: fontdue::Font, size: u32, scale: f32, radius: f32) -> (HashMap<char, CharacterGlyph>, Vec<u8>) {
    let padding = radius as u32;
    let spacing: u32 = 2; // spacing between glyphs in the atlas to prevent bleeding

    let characters: Vec<u8> = (32u8..127).collect();
    let sdf_glyphs: Vec<SdfGlyph> = characters
        .into_par_iter()
        .map(|u_char| {
            let ch = u_char as char;

            let (metrics, bitmap) = font.rasterize(ch, scale);

            let padded_width = metrics.width as u32 + (padding * 2);
            let padded_height = metrics.height as u32 + (padding * 2);

            // Pad the raw character bitmap and do sdf processing
            let mut padded_bitmap = vec![0u8; (padded_width * padded_height) as usize];
            for r in 0..metrics.height {
                for c in 0..metrics.width {
                    let src_idx = r * metrics.width + c;
                    let pad_idx = (r + padding as usize) * padded_width as usize + c + padding as usize;

                    padded_bitmap[pad_idx] = bitmap[src_idx];
                }
            }

            let sdf_bitmap = self::generate_sdf(&padded_bitmap, padded_width, padded_height, radius);

            SdfGlyph {
                ch, 
                metrics,
                bitmap: sdf_bitmap,
                width: padded_width,
                height: padded_height
            }
        })
        .collect();

    self::blit_glyphs(sdf_glyphs, spacing, size, radius)
}

/// blit character glyphs into a font atlas, and convert metrics into glyph bounds
fn blit_glyphs(glyphs: Vec<SdfGlyph>, spacing: u32, size: u32, radius: f32) -> (HashMap<char, CharacterGlyph>, Vec<u8>){
    let mut atlas_bitmap = vec![0u8; (size * size) as usize];
    let mut glyph_table = HashMap::new();

    let mut current_x: u32 = 0;
    let mut current_y: u32 = 0;
    let mut max_row_height: u32 = 0;

    for glyph in glyphs {
        // wrap to next row and add 2px spacing between glyphs
        if current_x + glyph.width + spacing > size {
            current_x = 0;
            current_y += max_row_height + spacing;
            max_row_height = 0;
        }
        max_row_height = max_row_height.max(glyph.height);

        // blit character sdf bitmap into atlas
        for r in 0..glyph.height {
            for c in 0..glyph.width {
                let src_idx = (r * glyph.width + c) as usize;

                let atlas_x = current_x + c;
                let atlas_y = current_y + r;
                let atlas_idx = (atlas_y * size + atlas_x) as usize;

                atlas_bitmap[atlas_idx] = glyph.bitmap[src_idx];
            }
        }

        // insert character glyph metrics into glyph table
        let uv_bounds = Vec4::new(
            current_x as f32 / size as f32,
            current_y as f32 / size as f32,
            glyph.width as f32 / size as f32,
            glyph.height as f32 / size as f32,
        );

        let plane_bounds = Vec4::new(
            glyph.metrics.bounds.xmin as f32 - radius,
            glyph.metrics.bounds.ymin as f32 - radius,
            glyph.metrics.width as f32 + (radius * 2.0),
            glyph.metrics.height as f32 + (radius * 2.0)
        );

        glyph_table.insert(glyph.ch, CharacterGlyph {
            plane_bounds,
            uv_bounds,
            advance: glyph.metrics.advance_width// + radius
        });

        // advance x coord for next character
        current_x += glyph.width + spacing;
    }

    (glyph_table, atlas_bitmap)
}

/// Generate a signed distance field (sdf) bitmap from an alpha mask bitmap.
/// 
/// * 'src' - the alpha mask bitmap as raw bytes
/// * 'width' - the width of the sdf bitmap
/// * 'height' - the height of the sdf bitmap
/// * 'radius' - the max search distance for the edge gradient in the sdf bitmap
fn generate_sdf(src: &[u8], width: u32, height: u32, radius: f32) -> Vec<u8> {
    let width = width as i32;
    let height = height as i32;
    let total_pixels = (width * height) as usize;

    // We maintain two separate vector grids: one for the interior of the text, one for the exterior.
    // This allows us to calculate an accurate "Signed" distance field from both sides of the edge.
    let mut grid_inside = vec![Point::infinity(); total_pixels];
    let mut grid_outside = vec![Point::infinity(); total_pixels];

    for y in 0..height {
        for x in 0..width {
            let idx = (y * width + x) as usize;
            let alpha = src[idx] as f32 / 255.0;
            
            if alpha > 0.5 { 
                grid_inside[idx] = Point { x: 0.0, y: 0.0 };
            } else {
                grid_outside[idx] = Point { x: 0.0, y: 0.0 };
            }
        }
    }

    // Helper macro/closure to perform sequential neighbor evaluation
    let compare = |grid: &mut Vec<Point>, x: i32, y: i32, nx: i32, ny: i32| {
        if nx >= 0 && nx < width && ny >= 0 && ny < height {
            let curr_idx = (y * width + x) as usize;
            let neigh_idx = (ny * width + nx) as usize;
            
            let n_pt = unsafe { *grid.get_unchecked(neigh_idx) };
            // Calculate relative offset step to this neighbor
            let new_pt = Point {
                x: n_pt.x + ((nx - x) as f32),
                y: n_pt.y + ((ny - y) as f32),
            };

            if new_pt.length_sq() < grid[curr_idx].length_sq() {
                grid[curr_idx] = new_pt;
            }
        }
    };

    // 2. THE FORWARD SWEEP (Top-to-Bottom, Left-to-Right)
    for y in 0..height {
        for x in 0..width {
            // Check Left, Top-Left, Top, Top-Right
            compare(&mut grid_inside, x, y, x - 1, y);
            compare(&mut grid_inside, x, y, x - 1, y - 1);
            compare(&mut grid_inside, x, y, x,     y - 1);
            compare(&mut grid_inside, x, y, x + 1, y - 1);

            compare(&mut grid_outside, x, y, x - 1, y);
            compare(&mut grid_outside, x, y, x - 1, y - 1);
            compare(&mut grid_outside, x, y, x,     y - 1);
            compare(&mut grid_outside, x, y, x + 1, y - 1);
        }
    }

    // 3. THE BACKWARD SWEEP (Bottom-to-Top, Right-to-Left)
    for y in (0..height).rev() {
        for x in (0..width).rev() {
            // Check Right, Bottom-Right, Bottom, Bottom-Left
            compare(&mut grid_inside, x, y, x + 1, y);
            compare(&mut grid_inside, x, y, x + 1, y + 1);
            compare(&mut grid_inside, x, y, x,     y + 1);
            compare(&mut grid_inside, x, y, x - 1, y + 1);

            compare(&mut grid_outside, x, y, x + 1, y);
            compare(&mut grid_outside, x, y, x + 1, y + 1);
            compare(&mut grid_outside, x, y, x,     y + 1);
            compare(&mut grid_outside, x, y, x - 1, y + 1);
        }
    }

    let inv_radius = 1.0 / radius;
    let dest: Vec<u8> = grid_inside
        .into_iter()
        .enumerate()
        .map(|(i, point)| {
            let is_inside = src[i] > 127;

            // Calculate absolute true Euclidean distance from our displacement vectors
            let dist = if is_inside {
                grid_outside[i].length_sq().sqrt()
            } else {
                point.length_sq().sqrt()
            };

            // Clamp distance to our max radius boundary, and normalize 0.0 to 1.0
            let normalized = dist.min(radius) * inv_radius * 0.5;

            // Apply our center-biased threshold (0.5 is the exact edge)
            let final_sdf = if is_inside {
                0.5 + normalized
            } else {
                0.5 - normalized
            };

            (final_sdf * 255.0).round() as u8
        })
        .collect();

    dest
}